name: Build Java Project

on:
  push:
    branches: [ main ]   # (a) Executa quando há push na branch principal

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Faz checkout do código-fonte
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Configura o ambiente Java (b)
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'   # ou 'zulu', 'corretto', etc.
          java-version: '21'

      # 3️⃣ Executa o build com Maven (c)
      - name: Build with Maven
        run: mvn clean package

      # 4️⃣ Publica o ficheiro JAR como artefacto (d)
      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: target/*.jar